# Generated by Django 5.2.6 on 2025-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
