# Generated by Django 5.2.6 on 2025-10-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime'), ('cricketers', 'Cricketers'), ('cars', 'Cars'), ('nature', 'Nature')], default='anime', max_length=50),
        ),
    ]
