import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../Navbar/Navbar";
import Footer from "../components/Footer";
import { AuthProvider } from "../context/AuthContext"; // ✅ import yahan hai
import AlertStack from "../components/ui/AlertStack";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sticke",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Wrap everything inside AuthProvider */}
        <AuthProvider>
          <div className="relative w-full flex items-center justify-center">
            <Navbar />
          </div>
          {children}
          <AlertStack />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
